### ISSUE TITLE
Hello, why does 360 detect a virus when using this program?

### ISSUE THREAD

**Issue by ghost** [l-urk/Bat-To-Exe-Converter-64-Bit-#1]
Hello, why does 360 detect a virus when using this program?

**Comment by l-urk** [comment]
Hi, the signature for the binary (exe) is unverified by most distributors. As you likely discovered, the will be for the official release which is no longer available, which is the reason why I am hosting this program.
Could you possibly share the exact details of the 360 logs so I can better buffer the program to prevent virus positive checks?
I want to assure users that this is the official BATTOEXE program.
